index:
    path: /
    controller: App\Controller\HelloController::index
mention:
    path: /mention
    controller: App\Controller\MentionController::index
sejour:
    path: /sejour
    controller: App\Controller\SejourController::index
info:
    path: /info
    controller: App\Controller\InfoController::index
long:
    path: /long
    controller: App\Controller\LongController::index
cours:
    path: /cours
    controller: App\Controller\CoursController::index
